nowo_password_toggle:
    toggle: true
    visible_icon: 'eye-slash'
    hidden_icon: 'eye'
    visible_label: 'Mostrar'
    hidden_label: 'Ocultar'
    button_classes: ['input-group-text', 'cursor-pointer']
    toggle_container_classes: ['form-password-toggle']
