babdev_pagerfanta:
    # The default view to use for your paginators.
    default_view: twig

    # The default Twig template to use for your paginators.
    default_twig_template: '@Pagerfanta/twitter_bootstrap5.html.twig'

    # The exception strategy to use when a paginator is out of range.
    exceptions_strategy:
        # The exception strategy for when the current page is out of range.
        out_of_range_page: to_http_not_found
        # The exception strategy for when the current page is not an integer.
        not_valid_current_page: to_http_not_found
