twig:
    file_name_pattern: '*.twig'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
        - '@NowoPasswordToggle/Form/toggle_password_widget.html.twig'

when@test:
    twig:
        strict_variables: true
