app_redirect:
    path: /
    controller: App\Controller\IndexController::redirectToLocale

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    trailing_slash_on_root: false
    prefix:
      en: '/en'
      es: '/es'
